source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'honeybadger', '~> 4.0'
gem 'jbuilder', '~> 2.7'
gem 'mongo', '2.14.0'
gem 'mongoid', '7.4.3'
gem 'puma', '~> 3.0'
gem 'rack-cors', '1.1.1'
gem 'rails', '~> 6'
gem 'rails_jwt_auth', '1.7.3'
gem 'rubyzip', '1.3.0'
gem 'shrine', '~> 2.17.1'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 6'
  gem 'factory_bot_rails'
  gem 'faker', '~> 1.7', '>= 1.7.3'
  gem 'database_cleaner', '~> 1.6', '>= 1.6.1'
  gem 'simplecov', :require => false
  gem 'mongoid-rspec'
  gem 'rspec_junit_formatter', '~> 0.3.0'
  gem 'webmock', '~> 3.1.0'
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
