include:
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      docker_build_context: "./"
      dockerfile_path: "./"
      dockerfile_filename: "Dockerfile"
      stage: "build_web"
      job_suffix: "_web"
      matrix:
        - RUNNER: build
          DOCKER_BUILD_PLATFORM: "linux/amd64"
    variables:
      CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      docker_build_context: "viscoll-xproc/"
      dockerfile_path: "viscoll-xproc/"
      dockerfile_filename: "Dockerfile"
      stage: "build_xproc"      
      job_suffix: "_xproc"
      matrix:
      - RUNNER: build
        DOCKER_BUILD_PLATFORM: "linux/amd64"
    variables:
      CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-xproc"
  - component: $CI_SERVER_FQDN/devops/gitlab/components/sast/trivy@~latest
    inputs:
      docker_tag_to_scan: "${CI_COMMIT_SHA}"
      job_image_tag: "29-dind"
      needs:
        - "amend_manifest_xproc"
      stage: "test"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_finalize@~latest
    inputs:
      needs_copy:
        - trivy_scan
 
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'development'

stages:
  - build_web
  - build_xproc
  - test
  - finalize


