include:
  - project: "devops/gitlab/ci-templates/docker"
    ref: "1.0.0"
    file:
      - ".build_docker_image.yml"
      - ".push_docker_image.yml"
      - ".remove_docker_image.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file:
      - ".shiftleft_container_scanning.yml"
      - ".trivy_container_scanning.yml"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'development'

stages:
  - sast:project
  - build:web
  - build:xproc
  - test
  - sast:web
  - sast:xproc
  - push:web
  - push:xproc
  - remove:web
  - remove:xproc

shiftleft_project_scanning:
  stage: sast:project
  extends:
    - .shiftleft_container_scanning
  tags:
    - build
  allow_failure: true

build_web_image:
  stage: build:web
  extends:
    - .build_docker_image
  needs:
    - shiftleft_project_scanning
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  tags:
    - build

build_xproc_image:
  stage: build:xproc
  extends:
    - .build_docker_image
  needs:
    - shiftleft_project_scanning
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-xproc"
    DOCKER_BUILD_CONTEXT: "viscoll-xproc/"
    DOCKERFILE_PATH: "viscoll-xproc/"
  tags:
    - build

rspec_api_test:
  stage: test
  image: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  services:
    - name: mongo:4.0
  needs:
    - build_web_image
    - build_xproc_image
  script:
    - cd "${CI_PROJECT_DIR}/viscoll-api/"
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
  artifacts:
    paths:
      - viscoll-api/rspec.xml
    expire_in: 1 week
    reports:
      junit: viscoll-api/rspec.xml
  rules:
    - if: $DISABLE_RSPEC_TEST == "true"
      when: never
    - exists:
        - viscoll-api/spec/**.rb
        - viscoll-api/spec/**/**.rb
  tags:
    - build

trivy_web_container_scanning:
  stage: sast:web
  extends:
    - .trivy_container_scanning
  needs:
    - build_web_image
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  tags:
    - build
  allow_failure: true

trivy_xproc_container_scanning:
  stage: sast:xproc
  extends:
    - .trivy_container_scanning
  needs:
    - build_xproc_image
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-xproc"
  tags:
    - build
  allow_failure: true

push_web_image_to_registry:
  stage: push:web
  extends:
    - .push_docker_image
  needs:
    - trivy_web_container_scanning
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
    DOCKER_IMAGE_NAME: "vceditor_web"
  tags:
    - build

push_xproc_image_to_registry:
  stage: push:xproc
  extends:
    - .push_docker_image
  needs:
    - trivy_xproc_container_scanning
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-xproc"
    DOCKER_IMAGE_NAME: "vceditor_xproc"
  tags:
    - build

remove_web_image:
  stage: remove:web
  extends:
    - .remove_docker_image
  needs:
    - push_web_image_to_registry
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  rules:
    - when: always
  tags:
    - build

remove_xproc_image:
  stage: remove:xproc
  extends:
    - .remove_docker_image
  needs:
    - push_xproc_image_to_registry
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-xproc"
  rules:
    - when: always
  tags:
    - build
