version: "3.4"
services:
  app:
    container_name: viscoll_web
    image: viscoll-web
    build:
      context: .
      dockerfile: Dockerfile.web
    command: server -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - xproc
  mongo:
    container_name: viscoll_mongo
    image: mongo:4.0
    volumes:
      - db:/data/db
  xproc:
    container_name: viscoll_xproc
    image: viscoll-xproc
    build:
      context: .
      dockerfile: Dockerfile.idrovora
    volumes:
      - xproc:/docs
    command: --http 2000 --http-doc-root /docs /xpl
    ports:
      - 2000:2000
volumes:
  db:
    name: viscoll_db
  xproc:
    name: viscoll_xproc
