version: "3.4"
services:
  app:
    image: 'quay.io/upennlibraries/vceditor_web:staging'
    command: server -b 0.0.0.0
    ports:
      - 80:3000
    depends_on:
      - mongo
      - xproc
  mongo:
    image: mongo:4.0
    volumes:
      - db:/data/db
  xproc:
    image: 'quay.io/upennlibraries/vceditor_idrovora:staging'
    volumes:
      - xproc:/docs
    command: --http 2000 --http-context-path /xproc --http-doc-root /docs /xpl
    ports:
      - 2000:2000
volumes:
  db:
    name: db
  xproc:
    name: xproc
