version: "3.7"

services:
  app:
    image: "quay.io/upennlibraries/vceditor_web:${RELEASE_TAG}"
    command: server -b 0.0.0.0
    environment:
      - MAILER_HOST
      - MAILER_DEFAULT_FROM
      - MAILER_DOMAIN
      - RELEASE_TAG
      - APPLICATION_HOST
      - PROJECT_URL
      - MAILER_USR
      - MAILER_PWD
      - ADMIN_EMAIL
      - SECRET_KEY_BASE
      - RAILS_ENV
      - RAILS_SERVE_STATIC_FILES
      - XPROC_URL
    depends_on:
      - mongo
      - xproc
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.staging-app.rule=Host(`${PROJECT_URL}`)"
        - "traefik.http.routers.staging-app.entrypoints=production"
        - "traefik.http.services.staging-app.loadbalancer.server.port=3000"
    networks:
      - internal
      - traefik

  mongo:
    image: mongo:4.0
    volumes:
      - db:/data/db
    networks:
      - internal

  xproc:
    image: "quay.io/upennlibraries/vceditor_idrovora:${RELEASE_TAG}"
    command:
      [
        "--http",
        "2000",
        "--http-context-path",
        "/xproc",
        "--http-doc-root",
        "/docs",
        "--http-cleanup-schedule",
        "0 0 * * * ?",
        "--http-job-max-age",
        "PT168H",
        "/xpl",
      ]
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.staging-xproc.rule=Host(`${PROJECT_URL}`) && PathPrefix(`/xproc`)"
        - "traefik.http.routers.staging-xproc.entrypoints=production"
        - "traefik.http.services.staging-xproc.loadbalancer.server.port=2000"
    networks:
      - internal
      - traefik
    volumes:
      - xproc:/docs

networks:
  internal:
  traefik:
    external: true

volumes:
  db:
    name: db
  xproc:
    name: xproc
